### ISSUE TITLE
unsupported format character S

### ISSUE THREAD

**Issue by xiaohong23** [miu200521358/pmx_tailor#4]
Hello, Miu

Thank you for creating this wonderful application.  I have got errors when I run it.     The error messages are attached.  Could you look at it? Thank you.
![2022-01-04_232639](https://user-images.githubusercontent.com/46474017/148145475-ecbe0967-0a36-42aa-88ed-98161b05b7a5.png)
![2022-01-04_232612](https://user-images.githubusercontent.com/46474017/148145495-28946b52-898e-48d2-961e-dc28aec8332e.png)

**Comment by miu200521358** [comment]
Thank you for your report!
Fixed in branch "work_01.00".
I distributed a pre-built beta version to the Nico Nico Douga user community.
Would you please give it a try?

https://com.nicovideo.jp/community/co5387214

------
ご報告ありがとうございます！
ブランチ「work_01.00」で修正を行いました。
私はニコニコ動画のユーザーコミュニティでビルド済みのベータ版を配布しました。
こちらを試してみていただけますでしょうか。

**Comment by xiaohong23** [comment]
Hi, Miu
Thanks a lot for solving this problem.  It works perfectly now.  I was wondering if you could add the function to let user to have the option to choose the language.  I tried to change my system language to English but pmx-tail didn't switch to English.  Thank you very much for this awesome program!!!
